import image0 from '../perks/perk0.png'; 
import image1 from '../perks/perk1.png'; 
import image2 from '../perks/perk2.png'; 
import image3 from '../perks/perk3.png';
import image4 from '../perks/perk4.png';
import image5 from '../perks/perk5.png'; 
import image6 from '../perks/perk6.png'; 
import image7 from '../perks/perk7.png'; 
import image8 from '../perks/perk8.png'; 
import image9 from '../perks/perk9.png'; 
import image10 from '../perks/perk10.png'; 
import image11 from '../perks/perk11.png'; 
import image12 from '../perks/perk12.png'; 
import image13 from '../perks/perk13.png'; 
import image14 from '../perks/perk14.png'; 
import image15 from '../perks/perk15.png'; 
import image16 from '../perks/perk16.png'; 
import image17 from '../perks/perk17.png'; 
import image18 from '../perks/perk18.png'; 
import image19 from '../perks/perk19.png'; 
import image20 from '../perks/perk20.png'; 
import image21 from '../perks/perk21.png'; 
import image22 from '../perks/perk22.png'; 
import image23 from '../perks/perk23.png'; 
import image24 from '../perks/perk24.png'; 
import image25 from '../perks/perk25.png'; 
import image26 from '../perks/perk26.png'; 
import image27 from '../perks/perk27.png'; 
import image28 from '../perks/perk28.png'; 
import image29 from '../perks/perk29.png'; 
import image30 from '../perks/perk30.png'; 
import image31 from '../perks/perk31.png';
export var perks=[];

perks.push(image0);
perks.push(image1);
perks.push(image2);
perks.push(image3);
perks.push(image4);
perks.push(image5);
perks.push(image6);
perks.push(image7);
perks.push(image8);
perks.push(image9);
perks.push(image10);
perks.push(image11);
perks.push(image12);
perks.push(image13);
perks.push(image14);
perks.push(image15);
perks.push(image16);
perks.push(image17);
perks.push(image18);
perks.push(image19);
perks.push(image20);
perks.push(image21);
perks.push(image22);
perks.push(image23);
perks.push(image24);
perks.push(image25);
perks.push(image26);
perks.push(image27);
perks.push(image28);
perks.push(image29);
perks.push(image30);
perks.push(image31);
